spring.application.name=Skill-Bridge

# Database
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/skillbridge}
spring.datasource.username=${DB_USERNAME:}
spring.datasource.password=${DB_PASSWORD:}

spring.jpa.hibernate.ddl-auto=update

# JWT
jwt.secret.key=${JWT_SECRET_KEY:}

server.servlet.context-path=/api
server.port=8080

# AI - Groq
spring.ai.openai.api-key=987354
spring.ai.openai.base-url=${AI_GROQ_BASE_URL:https://api.groq.com/openai}
spring.ai.openai.chat.options.model=${AI_GROQ_MODEL:llama-3.1-8b-instant}
spring.ai.openai.chat.options.temperature=0.3

# Mail
spring.mail.host=${MAIL_HOST:smtp-relay.brevo.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.from=${MAIL_FROM:}

# Frontend URL
frontend.url=${FRONTEND_URL:}
